version: '2'
services:
  fixedassetservice-postgresql:
    image: postgres:11.5
    # volumes:
    #     - ~/volumes/jhipster/fixedAssetService/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=fixedAssetService
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
