version: '2'
services:
  fixedassetservice-postgresql:
    image: postgres:11.5
    volumes:
      - ~/volumes/jhipster/fixedAssetService/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${PG_DATABASE_DEV_USER}
      - POSTGRES_PASSWORD=${PG_DATABASE_DEV_PASSWORD}
    ports:
      - 58213:5432
